### ISSUE TITLE
Encapsulate brian objects

### ISSUE THREAD

**Issue by ckarageorgkaneen** [Poirazi-Lab/dendrify#12]
Encapsulate brian objects in the same way brian, pytorch, etc. encapsulate other libraries (e.g. numpy, matplotlib)
e.g.
```python
import brian2 as b
from brian2.units import (ms, um, pA, nS, uS, ohm, cm, mV, uF, mvolt)
from dendrify import Soma, Dendrite, NeuronModel

b.prefs.codegen.target = 'numpy'
b.start_scope()    # allows running separate simulations in the same notebook
```
should be:
```python
import dendrify as d
from dendrify.units import (ms, um, pA, nS, uS, ohm, cm, mV, uF, mvolt)
d.prefs.codegen.target = 'numpy'
d.start_scope()
```

This makes development and usage easier, cleaner and less ambiguous.

**Comment by mpgl** [comment]
Although a nice idea, I don't think that this is currently necessary. I implemented this to some extend (users can create NeuronGroups directly from a NeuronModel), but encapsulating the entire Brian will create more problems that it will solve in my opinion. I like that currently there is a clear distinction between Dendrify and Brian features. Thank your for your suggestion however, I might consider this for the future.
