### ISSUE TITLE
Replace sys.exit() with specific error

### ISSUE THREAD

**Issue by ckarageorgkaneen** [Poirazi-Lab/dendrify#15]
`sys.exit()` raises `SystemError`. However, dendrify errors vary and are not `system`-related. So, always calling `sys.exit()` is misleading.

Suggestion: Replace `sys.exit()` calls with raising specific exceptions.

E.g. instead of this:

```python
if self.name == other.name:
    print(("ERROR: Cannot connect to compartments with the same name.\n"
           "Program exited"))
    sys.exit()
``` 

do this:

```python
if self.name == other.name:
    raise ValueError('Cannot connect to compartments with the same name')
```

See:
- https://stackoverflow.com/a/24065533 (best practices)
- https://docs.python.org/3/library/exceptions.html (for knowing which exceptions to use for different cases)
- https://docs.python.org/3/library/exceptions.html#exception-hierarchy (to get a sense of the exception hierarchy)

**Comment by mpgl** [comment]
sys.exit() raises a SystemExit error (not a SystemError). So I don't think that calling sys.exit() is misleading. One advantage of exiting in this way is that you avoid getting very long error messages that include traceback calls (see https://softhints.com/how-to-print-error-message-traceback-python/). However, I do agree that my previous implementation has some room for improvements (e.g. remove prints). Thank you for your suggestion.

**Comment by ckarageorgkaneen** [comment]
As far as simply exiting the program is concerned, `SystemExit` is not misleading. As far as user-friendliness and usability are concerned, it is. Because it is too generic, abrupt for the user and unhelpful for a developer. In the places where you use it, the errors are very specific. `SystemExit` is not as informative and it is normally used for scripts (not importable modules). Also, `SystemExit` is a special type of exception that won't be caught by a `try: ... except Exception: ...`. Specific errors help other developers that might build on top of yours catch them, if something goes wrong, and handle them however they want. Since this a library intended to be used elsewhere and not just a little script, `sys.exit()` is bad practice here.

Just raise a specific exception. That will both:
- cause the process to exit, as you intend
- notify the user with an informative backtrace (e.g. value error occured here, with a specific message)

It's up to the user of your library as to how to handle "very long error messages". E.g. if I wanna use `dendrify` in a script, I can just catch your specific error, and print my own message.

See:
- https://www.reddit.com/r/Python/comments/7xdi5r/is_sysexit_bad_practice/ (discussion on this topic)
- https://github.com/ScilifelabDataCentre/dds_cli/issues/78#issue-906152712 ("Doing a hard system exit is an absolute last resort.")
- https://mail.python.org/pipermail/python-list/2016-April/857869.html ("... How rude! Instead, let the 
exception bubble out...")

**Comment by mpgl** [comment]
Implemented in the development branch, will be pushed to main soon. Thanks
