### ISSUE TITLE
Make `pre` a positional argument (mandatory)

### ISSUE THREAD

**Issue by ckarageorgkaneen** [Poirazi-Lab/dendrify#16]
[`pre` is an optional argument](https://github.com/Poirazi-Lab/dendrify/blob/main/dendrify/compartment.py#L181).

However, [if `pre` is not given, you raise an exception](https://github.com/Poirazi-Lab/dendrify/blob/main/dendrify/compartment.py#L228).

Which implies that `pre` is mandatory and not optional. So, just make `pre` a positional argument, so that the user always provides it.

**Comment by mpgl** [comment]
Good idea, thanks. DONE
