### ISSUE TITLE
Replace exec statements

### ISSUE THREAD

**Issue by ckarageorgkaneen** [Poirazi-Lab/dendrify#17]
Putting assignment statements in strings and using `exec()` (e.g. [this](https://github.com/Poirazi-Lab/dendrify/blob/main/dendrify/neuronmodel.py#L299)) leads to having to do weird things, beforehand. Like, parsing the guts of the main module just to get a hold of a [neuron group object](https://github.com/Poirazi-Lab/dendrify/blob/ca105bba66235de90f16533e633ade207d32c54a/dendrify/neuronmodel.py#L269). All this is unnecessarily complex.

There are two better ways of doing such things:

1. One alternative is just having the dendrify `NeuronModel` hold a reference of the brian `NeuronGroup`. Therefore, to set the rest potential, for example, you can do something like this:

```python
for cpt in self._compartments:
    setattr(self.linked_ng, f'V_{cpt.name}', self.linked_ng.namespace[f'EL_{cpt.name}'])
```  

2. Another simple way would be to implement the suggestion: https://github.com/Poirazi-Lab/dendrify/issues/13#issue-1559139993, by merging your `NeuronModel` with the brian `NeuronGroup`. Then, you could just be able to do this: 

```python
for cpt in self._compartments:
    setattr(self, f'V_{cpt.name}', self.namespace[f'EL_{cpt.name}'])
```
since `self` would itself be just an instance of a brian `NeuronGroup` subclass.

**Comment by mpgl** [comment]
Issue resolved, thank you for your recommendations,
